{-# LANGUAGE NoFieldSelectors #-}

module TreeSitter.Prismatic.Internal.Language.Core where

import Data.Array (Array)
import Data.Ix (Ix)
import Data.Kind (Type)
import Data.Proxy (Proxy)
import Data.Text (Text)
import Data.Word (Word16, Word32, Word8)
import GHC.Generics (Generic)
import TreeSitter.Prismatic.Internal.Language.Raw (RawLang)
import TreeSitter.Prismatic.Internal.Language.SymbolType (SymbolType)
import TreeSitter.Prismatic.Internal.Language.SymbolType qualified as SymbolType

{- | Typeclass for phantom datatypes marking Tree-sitter grammars

  This class contains all of the code generated by stage 2 of
  this package's template haskell code from the 'RawLang' and
  language metadata.
  The stage 3 macros build out helper definitions from the
  code defined here.
-}
class LangCore l where
    langCoreSymbols :: Proxy l -> Array Word16 (SymbolType, Text)
    langCoreFields :: Proxy l -> Array Word16 Text
    langCoreName :: Proxy l -> Text

    -- langCoreVersion :: Proxy l -> LangVersion
    langCoreRaw :: Proxy l -> IO RawLang

data LangVersion = LangVersion
    { major :: !Word8
    , minor :: !Word8
    , patch :: !Word8
    }
    deriving (Eq, Ord, Show, Generic)

newtype Symbol' l = Symbol' Word16
    deriving (Eq, Ord)
type role Symbol' nominal

class (Bounded l, Enum l, Ix l) => Symbol l where
    symbolType :: l -> SymbolType
    symbolName :: l -> Text

-- instance

class (Bounded l, Enum l, Ix l) => FieldId l where
    fieldName :: l -> Text

-- type FieldId a = Symbol a
